// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0odHWE3pi6QN2SkAh8QcnSUsBAi1G2DM',
    appId: '1:251723562096:web:f21f407549a7aca27048b5',
    messagingSenderId: '251723562096',
    projectId: 'fic-takeuchi-project1',
    authDomain: 'fic-takeuchi-project1.firebaseapp.com',
    storageBucket: 'fic-takeuchi-project1.appspot.com',
    measurementId: 'G-4G3VTZHYBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArToBMJoSGdfHIkFzmm4xT6ZLjYb8qYw4',
    appId: '1:251723562096:android:e2cdc5d210a94aa17048b5',
    messagingSenderId: '251723562096',
    projectId: 'fic-takeuchi-project1',
    storageBucket: 'fic-takeuchi-project1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0odHWE3pi6QN2SkAh8QcnSUsBAi1G2DM',
    appId: '1:251723562096:web:0d98305ac594de277048b5',
    messagingSenderId: '251723562096',
    projectId: 'fic-takeuchi-project1',
    authDomain: 'fic-takeuchi-project1.firebaseapp.com',
    storageBucket: 'fic-takeuchi-project1.appspot.com',
    measurementId: 'G-KDGB2X8KYC',
  );
}
