// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiSz9SiBWCsB6TNbVGZX1I25Q9V_GTfc',
    appId: '1:401818502669:web:f92d92109679877c3bb744',
    messagingSenderId: '401818502669',
    projectId: 'fic-takeuchi-project',
    authDomain: 'fic-takeuchi-project.firebaseapp.com',
    storageBucket: 'fic-takeuchi-project.appspot.com',
    measurementId: 'G-MSF4J1Y85N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0iNEEIix3YoFrIeq8Y5f3cLmVWz_5QNw',
    appId: '1:401818502669:android:993c4d7440e639aa3bb744',
    messagingSenderId: '401818502669',
    projectId: 'fic-takeuchi-project',
    storageBucket: 'fic-takeuchi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATiSz9SiBWCsB6TNbVGZX1I25Q9V_GTfc',
    appId: '1:401818502669:web:9667b045568830343bb744',
    messagingSenderId: '401818502669',
    projectId: 'fic-takeuchi-project',
    authDomain: 'fic-takeuchi-project.firebaseapp.com',
    storageBucket: 'fic-takeuchi-project.appspot.com',
    measurementId: 'G-CT9ZZNKGJ3',
  );

}